version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    entrypoint: java
    #command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    restart: always
    volumes:
      - dynamodb-data:/data
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb

volumes:
    dynamodb-data:
        external: true
