version: 2.1

references:
  filter_all_branches: &filter_all_branches
    branches:
      only: /.*/
    tags:
      ignore: /.*/
  filters_only_master_branch: &filters_only_master_branch
    branches:
      only: /master/

orbs:
  change-api: financial-times/change-api@1
  ft-golang-ci: financial-times/golang-ci@1

commands:
  test:
    steps:
      - checkout
      - run:
          name: Install package
          command: npm install .
      - run:
          name: Lint
          command: npm run lint

jobs:
  lint_test:
    docker:
      - image: node:lts-alpine3.20
    steps:
      - test

workflows:
  version: 2
  test:
    jobs:
      - lint_test:
          filters:
            <<: *filter_all_branches
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context:
            - cm-team-snyk
            - cm-team-github
          filters:
            <<: *filter_all_branches
  release:
    jobs:
      - change-api/change-log:
          system-code: 'upp-exports'
          environment: 'prod'
          slack-channels: 'cm-changes,ft-changes'
          filters:
            <<: *filters_only_master_branch
